version: 2.1
orbs:
  node: circleci/node@1.1.6
  doctl: digitalocean/cli@1.0.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
      - run: yarn test
  doctl/install_and_initialize_cli:
    context: myContext
    executor: doctl/default
workflows:
    test:
      jobs:
        - test
